### ISSUE TITLE
Tracking of `FIXME`

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2499]
There are some todo and fixme items in the source code. Here's an issue to try and keep track of them, and to link to the relevant issues if they already exist.

**JP Core**

- [ ] #396
https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-core/src/main/java/com/github/javaparser/CommentsInserter.java#L60-L75

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-core/src/main/java/com/github/javaparser/printer/ConcreteSyntaxModel.java#L241-L248

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-core/src/main/java/com/github/javaparser/printer/concretesyntaxmodel/CsmElement.java#L133-L136

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedReferenceType.java#L179-L184

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedReferenceType.java#L189-L194

**JSS Core**

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/ConstructorResolutionLogic.java#L225-L229

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/SymbolSolver.java#L101-L115

- [ ] I believe this fixme no longer applies given that it is implement above it...?
https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typeinference/ControlFlowLogic.java#L306-L308

- [ ] https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typeinference/TypeHelper.java#L70-L73

- [ ] I believe this fixme no longer applies given that it is implement above it...?
https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typeinference/TypeHelper.java#L152-L155

- [ ] Given the commented-out `//throw new UnsupportedOperationException();`, is this a hangover or is it still applicable...?
https://github.com/javaparser/javaparser/blob/1e152bd8dd38adc5f31b2f882ac4fd952d42dc0b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typeinference/constraintformulas/TypeCompatibleWithType.java#L88-L103

**JSS Tests**
There are six matches here, but appears to be in the "old" versions of code that are used within tests thus can likely just be ignored.

**Comment by matozoid** [comment]
Wouldn't it be easier if these were separate issues?
